id: P688E4E68
initial_creation_type: input
source_metadata:
  title: Yangthang Rinpoche Series
  language: bo
  description: Texts by Domang Yangthang Rinpoche (mdo mang g.yang thang rin po che,
    1929–2016), the renowned incarnation of Domang Dorje Dechen Lingpa (1857–1928).
  volume:
    2629ce07e915477bb0ca5b3f2a4adb87:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    e1427c3e9d674dd89f372f56fbbb6225:
      title: Prayer for the Flourishing of the Dzogchen Teachings of Sogyal Rinpoche,
        the incarnation of Lerab Lingpa
      parent: Prayers
created_at: '2022-03-01T02:01:26.943118'
last_modified_at: '2022-03-01T02:01:26.943121'
statistics:
  total_words: 2418
  total_non_words: 227
quality:
  non_words_ratio: 0.09
